---
- name: Build and Push Container Image
  hosts: "all"

  environment:
    registry: "{{ docker_registry | default('registry.scs.community') }}"
    project: "{{ registry_project }}"
    repository: "{{ image_repository }}"
    container_name: "{{ container_name | default( zuul.project.short_name ) }}"
    containerfile_path: "{{ containerfile_path | default('.') }}"
    version: "{{ zuul['tag'] | default('latest') }}"
    licenses: "{{ licenses | default('') }}"

  tasks:
    - name: "Log into registry"
      community.docker.docker_login:
        registry_url: "{{ docker_registry }}"
        username: "{{ secret.DOCKER_USERNAME }}"
        password: "{{ secret.DOCKER_PASSWORD }}"
      when: push_image | bool

    - name: "Run build script"
      ansible.builtin.shell:
        executable: "/bin/bash"
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          created=$(date --rfc-3339=ns)
          revision=$(git rev-parse --short HEAD)

          docker buildx build \
              --label "org.opencontainers.image.created=${created}" \
              --label "org.opencontainers.image.documentation=https://docs.scs.community" \
              --label "org.opencontainers.image.licenses=ASL 2.0" \
              --label "org.opencontainers.image.revision=${revision}" \
              --label "org.opencontainers.image.source={{ zuul.project.canonical_name }}" \
              --label "org.opencontainers.image.title=${container_name}" \
              --label "org.opencontainers.image.url=https://scs.community" \
              --label "org.opencontainers.image.vendor=Sovereign Cloud Stack SCS" \
              --label "org.opencontainers.image.version=$version" \
              --load \
              --tag "$revision" \
              ${containerfile_path}
      when: custom_build_script is not defined
      changed_when: true
    
    - name: "Run custom build script"
      ansible.builtin.shell:
        executable: "/bin/bash"
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          {{ custom_build_script | indent(width=10, indentfirst=False) }}
      when: custom_build_script is defined
      changed_when: true

    - name: Run push script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          revision=$(git rev-parse --short HEAD)

          docker tag "$revision" "$repository:$version"
          docker push "$repository:$version"

      when: push_image | bool
      changed_when: true
      no_log: true
