---
- hosts: all
  debugger: always
  tasks:
    - name: Install ansible-galaxy
      become: true
      ansible.builtin.apt:
        name: ansible
        update_cache: yes
        state: present

    - name: Install python3-openstacksdk
      become: true
      ansible.builtin.apt:
        name: python3-openstacksdk
        state: present

    - name: Install collection openstack.cloud
      community.general.ansible_galaxy_install:
        type: collection
        name: openstack.cloud

    - name: Create cloud config dir
      ansible.builtin.file:
        path: "~/.config/openstack"
        state: directory
        recurse: true
        mode: "0700"

    - name: Create cloud config file
      ansible.builtin.copy:
        content: "{{ clouds_conf.credentials }}"
        dest: "~/.config/openstack/clouds.yaml"
        mode: "0600"
      no_log: true

    - name: List compute flavors
      openstack.cloud.compute_flavor_info:
        cloud: wavestack
      register: flavors

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: flavors.openstack_flavors
        verbosity: 4