---
- hosts: all
  tasks:
    - name: Install ansible-galaxy
      become: true
      ansible.builtin.apt:
        name: ansible
        update_cache: yes
        state: present

    - name: Install collection openstack.cloud
      become: true
      community.general.ansible_galaxy_install:
        type: collection
        name: openstack.cloud
