---
- hosts: all
  tasks:
    - name: Install ansible-galaxy
      become: true
      ansible.builtin.apt:
        name: ansible
        update_cache: yes
        state: present

    - name: Install python3-openstacksdk
      become: true
      ansible.builtin.apt:
        name: python3-openstacksdk
        state: present

    - name: Install collection openstack.cloud
      community.general.ansible_galaxy_install:
        type: collection
        name: openstack.cloud
      register: install_collection_openstackcloud
      until: "install_collection_openstackcloud is not failed"
      retries: 5
      delay: 5
